In [2]:
import cptac
import warnings
warnings.filterwarnings('ignore')

ds = cpta

NameError: name 'cpta' is not defined

In [2]:
ds.list_data_sources()

              Data type    Available sources
0                   CNV         [bcm, washu]
1          circular_RNA                [bcm]
2                 miRNA         [bcm, washu]
3     phosphoproteomics         [bcm, umich]
4            proteomics         [bcm, umich]
5       transcriptomics  [bcm, broad, washu]
6   ancestry_prediction         [harmonized]
7      somatic_mutation  [harmonized, washu]
8              clinical               [mssm]
9             follow-up               [mssm]
10      medical_history               [mssm]
11     acetylproteomics              [umich]
12            cibersort              [washu]
13           hla_typing              [washu]
14         tumor_purity              [washu]
15                xcell              [washu]

In [ ]:
import pandas as pd

proteomics = pd.read_csv('/home/franziska/bachelor/ProteomIQ/data/luad/proteomics_raw.csv', header=[0,1], index_col=0)
clinical = pd.read_csv('/home/franziska/bachelor/ProteomIQ/data/luad/clinical.csv', index_col=0)

both = proteomics.index.intersection(clinical.index)

print(f"Proteomics samples: {len(proteomics)}")
print(f"Clinical samples: {len(clinical)}")
print(f"Samples in both datasets: {len(both)}")

print(f"Total rows: {len(proteomics)}")
print(f"Unique patient IDs: {len(proteomics.index.unique())}")

In [11]:
# Explore clinical columns LUAD
print(list(clinical.columns))
print(f"end={len(clinical.columns)} columns in clinical dataset")

clinical.isnull().sum().sort_values(ascending=False).head(50)

['tumor_code', 'discovery_study', 'type_of_analyzed_samples', 'confirmatory_study', 'type_of_analyzed_samples.1', 'age', 'sex', 'race', 'ethnicity', 'ethnicity_race_ancestry_identified', 'Inferred ancestry', 'collection_in_us', 'participant_country', 'maternal_grandmother_country', 'maternal_grandfather_country', 'paternal_grandmother_country', 'paternal_grandfather_country', 'deaf_or_difficulty_hearing', 'blind_or_difficulty_seeing', 'difficulty_concentrating_remembering_or_making_decisions', 'difficulty_walking_or_climbing_stairs', 'difficulty_dressing_or_bathing', 'difficulty_doing_errands', 'consent_form_signed', 'case_stopped', 'tumor_site', 'tumor_site_other', 'tumor_laterality', 'tumor_focality', 'tumor_size_cm', 'histologic_type', 'histologic_grade', 'tumor_necrosis', 'margin_status', 'ajcc_tnm_cancer_staging_edition_used', 'pathologic_staging_primary_tumor_pt', 'pathologic_staging_regional_lymph_nodes_pn', 'number_of_lymph_nodes_examined', 'number_of_lymph_nodes_positive_for_tumor_by_he_staining', 'clinical_staging_distant_metastasis_cm', 'pathologic_staging_distant_metastasis_pm', 'specify_distant_metastasis_documented_sites', 'residual_tumor', 'tumor_stage_pathological', 'paraneoplastic_syndrome_present', 'ancillary_studies_immunohistochemistry_performed', 'ancillary_studies_immunohistochemistry_type_and_result', 'ancillary_studies_other_testing_performed', 'ancillary_studies_other_testing_type_and_result', 'performance_status_assessment_ecog_performance_status_score', 'performance_status_assessment_karnofsky_performance_status_score', 'number_of_lymph_nodes_positive_for_tumor_by_ihc_staining', 'perineural_invasion', 'height_at_time_of_surgery_cm', 'weight_at_time_of_surgery_kg', 'bmi', 'history_of_cancer', 'alcohol_consumption', 'tobacco_smoking_history', 'age_at_which_the_participant_started_smoking', 'age_at_which_the_participant_stopped_smoking', 'on_the_days_participant_smoked_how_many_cigarettes_did_he_she_usually_smoke', 'number_of_pack_years_smoked', 'was_the_participant_exposed_to_secondhand_smoke', 'exposure_to_secondhand_smoke_in_household_during_participants_childhood', 'exposure_to_secondhand_smoke_in_participants_current_household', 'number_of_years_participant_has_consumed_more_than_2_drinks_per_day_for_men_and_more_than_1_drink_per_day_for_women', 'cancer_type', 'history_source', 'history_of_any_treatment', 'medical_record_documentation_of_this_history_of_cancer_and_treatment', 'medical_condition', 'history_of_treatment', 'history_source.1', 'medication_name_vitamins_supplements', 'history_source.2', 'blood_collection_minimum_required_blood_collected', 'blood_collection_number_of_blood_tubes_collected', 'tumor_tissue_collection_tumor_type', 'tumor_tissue_collection_number_of_tumor_segments_collected', 'tumor_tissue_collection_clamps_used', 'tumor_tissue_collection_frozen_with_oct', 'normal_adjacent_tissue_collection_number_of_normal_segments_collected', 'follow_up_period', 'is_this_patient_lost_to_follow-up', 'vital_status_at_date_of_last_contact', 'number_of_days_from_date_of_initial_pathologic_diagnosis_to_date_of_last_contact', 'number_of_days_from_date_of_initial_pathologic_diagnosis_to_date_of_death', 'cause_of_death', 'number_of_days_from_date_of_collection_to_date_of_last_contact', 'number_of_days_from_date_of_collection_to_date_of_death', 'adjuvant_post-operative_radiation_therapy', 'adjuvant_post-operative_pharmaceutical_therapy', 'adjuvant_post-operative_immunological_therapy', 'tumor_status_at_date_of_last_contact_or_death', 'measure_of_success_of_outcome_at_the_completion_of_initial_first_course_treatment', 'measure_of_success_of_outcome_at_date_of_last_contact_or_death', 'ecog_performance_status_score_at_date_of_last_contact_or_death', 'karnofsky_performance_status_score_at_date_of_last_contact_or_death', 'performance_status_scale_timing_at_date_of_last_contact_or_death', 'measure_of_success_of_outcome_at_first_NTE', 'ecog_performance_status_score_at_first_NTE', 'karnofsky_performance_status_score_at_first_NTE', 'performance_status_scale_timing_at_first_NTE', 'new_tumor_after_initial_treatment', 'number_of_days_from_date_of_initial_pathologic_diagnosis_to_date_of_new_tumor_event_after_initial_treatment', 'type_of_new_tumor', 'site_of_new_tumor', 'other_site_of_new_tumor', 'diagnostic_evidence_of_recurrence_or_relapse', 'additional_surgery_for_new_tumor_loco-regional', 'additional_surgery_for_new_tumor_metastasis', 'residual_tumor_after_surgery_for_new_tumor', 'additional_treatment_radiation_therapy_for_new_tumor', 'additional_treatment_pharmaceutical_therapy_for_new_tumor', 'additional_treatment_immuno_for_new_tumor', 'number_of_days_from_date_of_initial_pathologic_diagnosis_to_date_of_additional_surgery_for_new_tumor_event_loco-regional', 'number_of_days_from_date_of_initial_pathologic_diagnosis_to_date_of_additional_surgery_for_new_tumor_event_metastasis', 'Recurrence-free survival, days', 'Recurrence-free survival from collection, days', 'Recurrence status (1, yes; 0, no)', 'Overall survival, days', 'Overall survival from collection, days', 'Survival status (1, dead; 0, alive)']
end=124 columns in clinical dataset

perineural_invasion                                                                                                         111
number_of_days_from_date_of_initial_pathologic_diagnosis_to_date_of_additional_surgery_for_new_tumor_event_metastasis       110
number_of_days_from_date_of_initial_pathologic_diagnosis_to_date_of_additional_surgery_for_new_tumor_event_loco-regional    110
exposure_to_secondhand_smoke_in_household_during_participants_childhood                                                     109
exposure_to_secondhand_smoke_in_participants_current_household                                                              107
type_of_analyzed_samples.1                                                                                                  104
medical_record_documentation_of_this_history_of_cancer_and_treatment                                                        103
history_of_any_treatment                                                                                                    103
number_of_years_participant_has_consumed_more_than_2_drinks_per_day_for_men_and_more_than_1_drink_per_day_for_women         103
cancer_type                                                                                                                 103
history_source                                                                                                              103
other_site_of_new_tumor                                                                                                     102
additional_surgery_for_new_tumor_loco-regional                                                                              101
additional_surgery_for_new_tumor_metastasis                                                                                  99
residual_tumor_after_surgery_for_new_tumor                                                                                   92
site_of_new_tumor                                                                                                            88
additional_treatment_radiation_therapy_for_new_tumor                                                                         88
number_of_days_from_date_of_initial_pathologic_diagnosis_to_date_of_new_tumor_event_after_initial_treatment                  88
additional_treatment_pharmaceutical_therapy_for_new_tumor                                                                    88
additional_treatment_immuno_for_new_tumor                                                                                    88
Recurrence-free survival from collection, days                                                                               88
Recurrence-free survival, days                                                                                               88
type_of_new_tumor                                                                                                            88
diagnostic_evidence_of_recurrence_or_relapse                                                                                 88
cause_of_death                                                                                                               87
number_of_days_from_date_of_collection_to_date_of_death                                                                      87
number_of_days_from_date_of_initial_pathologic_diagnosis_to_date_of_death                                                    87
ancillary_studies_other_testing_type_and_result                                                                              83
age_at_which_the_participant_stopped_smoking                                                                                 83
measure_of_success_of_outcome_at_date_of_last_contact_or_death                                                               82
tumor_site_other                                                                                                             81
medication_name_vitamins_supplements                                                                                         61
history_source.2                                                                                                             61
number_of_pack_years_smoked                                                                                                  56
age_at_which_the_participant_started_smoking                                                                                 49
on_the_days_participant_smoked_how_many_cigarettes_did_he_she_usually_smoke                                                  49
history_source.1                                                                                                             48
history_of_treatment                                                                                                         48
medical_condition                                                                                                            48
ancillary_studies_immunohistochemistry_type_and_result                                                                       42
number_of_days_from_date_of_collection_to_date_of_last_contact                                                               28
measure_of_success_of_outcome_at_first_NTE                                                                                   26
specify_distant_metastasis_documented_sites                                                                                  21
tumor_laterality                                                                                                              4
adjuvant_post-operative_radiation_therapy                                                                                     4
karnofsky_performance_status_score_at_date_of_last_contact_or_death                                                           4
ecog_performance_status_score_at_date_of_last_contact_or_death                                                                4
is_this_patient_lost_to_follow-up                                                                                             4
follow_up_period                                                                                                              4
tumor_tissue_collection_clamps_used                                                                                           4
dtype: int64

In [12]:
clinical.head(10)

,tumor_code,discovery_study,type_of_analyzed_samples,confirmatory_study,type_of_analyzed_samples.1,age,sex,race,ethnicity,ethnicity_race_ancestry_identified,...,additional_treatment_pharmaceutical_therapy_for_new_tumor,additional_treatment_immuno_for_new_tumor,number_of_days_from_date_of_initial_pathologic_diagnosis_to_date_of_additional_surgery_for_new_tumor_event_loco-regional,number_of_days_from_date_of_initial_pathologic_diagnosis_to_date_of_additional_surgery_for_new_tumor_event_metastasis,"Recurrence-free survival, days","Recurrence-free survival from collection, days","Recurrence status (1, yes; 0, no)","Overall survival, days","Overall survival from collection, days","Survival status (1, dead; 0, alive)"
Patient_ID,,,,,,,,,,,,,,,,,,,,,
11LU013,LUAD,Yes,Tumor,No,NaN,59,Male,Unknown,Unknown,Asian,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
11LU016,LUAD,Yes,Tumor,No,NaN,62,Male,Unknown,Unknown,Asian,...,NaN,NaN,NaN,NaN,NaN,NaN,0,445.0,441.0,1.0
11LU022,LUAD,Yes,Tumor,No,NaN,53,Male,Unknown,Unknown,Asian,...,NaN,NaN,NaN,NaN,NaN,NaN,0,7.0,0.0,0.0
11LU035,LUAD,Yes,Tumor,No,NaN,59,Male,Unknown,Unknown,Asian,...,NaN,NaN,NaN,NaN,NaN,NaN,0,7.0,0.0,0.0
C3L-00001,LUAD,Yes,Tumor_and_Normal,No,NaN,61,Female,White,Not Hispanic or Latino,Caucasian,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1837.0,1837.0,0.0
C3L-00009,LUAD,Yes,Tumor_and_Normal,No,NaN,76,Male,White,Not Hispanic or Latino,Caucasian,...,NaN,NaN,NaN,NaN,NaN,NaN,0,577.0,586.0,1.0
C3L-00080,LUAD,Yes,Tumor_and_Normal,No,NaN,58,Male,White,Not Hispanic or Latino,Caucasian,...,No,No,NaN,NaN,1000.0,1000.0,1,1805.0,1805.0,0.0
C3L-00083,LUAD,Yes,Tumor_and_Normal,No,NaN,71,Male,White,Not Hispanic or Latino,Caucasian,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1790.0,1790.0,0.0
C3L-00093,LUAD,Yes,Tumor_and_Normal,No,NaN,66,Female,White,Not Hispanic or Latino,Caucasian,...,No,No,NaN,NaN,382.0,382.0,1,1703.0,1703.0,1.0
C3L-00094,LUAD,Yes,Tumor_and_Normal,No,NaN,69,Male,White,Not Hispanic or Latino,Caucasian,...,Yes,No,NaN,NaN,638.0,638.0,1,889.0,889.0,1.0

In [14]:
clinical.isnull().sum().sort_values().head(30)

tumor_code                                                  0
discovery_study                                             0
type_of_analyzed_samples                                    0
confirmatory_study                                          0
age                                                         0
sex                                                         0
race                                                        0
ethnicity                                                   0
participant_country                                         0
ethnicity_race_ancestry_identified                          0
Inferred ancestry                                           0
collection_in_us                                            0
maternal_grandfather_country                                0
maternal_grandmother_country                                0
paternal_grandmother_country                                0
paternal_grandfather_country                                0
case_stopped                                                0
deaf_or_difficulty_hearing                                  0
blind_or_difficulty_seeing                                  0
difficulty_concentrating_remembering_or_making_decisions    0
difficulty_walking_or_climbing_stairs                       0
difficulty_dressing_or_bathing                              0
difficulty_doing_errands                                    0
consent_form_signed                                         0
histologic_type                                             0
tumor_site                                                  0
tumor_size_cm                                               0
tumor_focality                                              0
histologic_grade                                            0
ajcc_tnm_cancer_staging_edition_used                        0
dtype: int64

In [15]:
cols = ['age', 'sex', 'race', 'histologic_type', 'tumor_size_cm', 'tumor_focality', 'histologic_grade']
for col in cols:
    print(f"\n--- {col} ---")
    print(clinical[col].value_counts(dropna=False))

--- age ---
age
58    8
56    8
59    7
69    7
62    5
64    5
68    5
61    4
76    4
71    4
66    4
72    4
57    4
70    3
67    3
77    3
65    3
54    3
48    3
79    2
60    2
81    2
73    2
49    2
55    2
45    2
53    1
35    1
80    1
78    1
52    1
40    1
44    1
63    1
46    1
37    1
Name: count, dtype: int64

--- sex ---
sex
Male      73
Female    38
Name: count, dtype: int64

--- race ---
race
Unknown                             74
White                               34
American Indian or Alaska Native     1
Asian                                1
Black or African American            1
Name: count, dtype: int64

--- histologic_type ---
histologic_type
Adenocarcinoma                                               57
Acinar adenocarcinoma                                        25
Solid adenocarcinoma                                          7
not specified                                                 4
Papillary adenocarcinoma                                      3
Lepidic adenocarcinoma                                        2
Adenocarcinoma, acinar predominant                            1
Adenocarcinoma, micropapillary and acinar                     1
Lepidic adenocarcinoma, Invasive mucinous adenocarcinoma      1
Squamous cell carcinoma                                       1
Adenocaricnoma, mixed sub-type (solid and acinar)             1
Mixed acinar and micropapillary adenocarcinoma                1
Adenosquamous carcinoma (approx. 75% adeno, 25% squamous)     1
Acinar adenocarcinoma and papillary adenocarcinoma            1
Adenocarcinoma, mixed subtype                                 1
Adenosquamous carcinoma                                       1
Colloid adenocarcinoma                                        1
adenocarcinoma with neuroendocrine differentiation            1
squamous versus adenocarcinoma pending IHC                    1
Name: count, dtype: int64

--- tumor_size_cm ---
tumor_size_cm
4.0     16
5.0     13
3.5     12
2.5     10
3.0      9
6.0      8
4.5      7
2.0      5
2.2      4
2.8      4
6.5      2
3.2      2
3.1      2
5.5      2
3.7      1
1.8      1
2.4      1
1.9      1
7.5      1
3.3      1
2.7      1
2.1      1
4.2      1
12.0     1
5.2      1
1.2      1
1.5      1
3.8      1
5.8      1
Name: count, dtype: int64

--- tumor_focality ---
tumor_focality
Unifocal      105
Multifocal      6
Name: count, dtype: int64

--- histologic_grade ---
histologic_grade
G2 Moderately differentiated                                         59
G3 Poorly differentiated                                             39
G1 Well differentiated                                                7
GX Grading is not applicable, cannot be assessed or not specified     6
Name: count, dtype: int64

In [ ]:
# check age column
print(f"Total: {len(clinical['age'])}")
print(f"NaN count: {clinical['age'].isna().sum()}")
print(f"Unique values: {clinical['age'].nunique()}")

Total: 111
NaN count: 0
Unique values: 36

In [22]:
# check sex column
print(clinical['sex'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['sex'].isna().sum()}")

sex
Male      73
Female    38
NaN count: 0

In [23]:
# check tumor_stage_pathologic column
print(clinical['tumor_stage_pathological'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['tumor_stage_pathological'].isna().sum()}")

tumor_stage_pathological
Stage I      59
Stage II     30
Stage III    21
Stage IV      1
NaN count: 0

In [24]:
# check histologic_grade column
print(clinical['histologic_grade'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['histologic_grade'].isna().sum()}")

histologic_grade
G2 Moderately differentiated                                         59
G3 Poorly differentiated                                             39
G1 Well differentiated                                                7
GX Grading is not applicable, cannot be assessed or not specified     6
NaN count: 0

In [27]:
# check histologic_type column
print(clinical['histologic_type'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['histologic_type'].isna().sum()}")

histologic_type
Adenocarcinoma                                               57
Acinar adenocarcinoma                                        25
Solid adenocarcinoma                                          7
not specified                                                 4
Papillary adenocarcinoma                                      3
Lepidic adenocarcinoma                                        2
Adenocarcinoma, acinar predominant                            1
Adenocarcinoma, micropapillary and acinar                     1
Lepidic adenocarcinoma, Invasive mucinous adenocarcinoma      1
Squamous cell carcinoma                                       1
Adenocaricnoma, mixed sub-type (solid and acinar)             1
Mixed acinar and micropapillary adenocarcinoma                1
Adenosquamous carcinoma (approx. 75% adeno, 25% squamous)     1
Acinar adenocarcinoma and papillary adenocarcinoma            1
Adenocarcinoma, mixed subtype                                 1
Adenosquamous carcinoma                                       1
Colloid adenocarcinoma                                        1
adenocarcinoma with neuroendocrine differentiation            1
squamous versus adenocarcinoma pending IHC                    1
NaN count: 0

In [28]:
# check tumor_size_cm column
print(clinical['tumor_size_cm'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['tumor_size_cm'].isna().sum()}")

tumor_size_cm
4.0     16
5.0     13
3.5     12
2.5     10
3.0      9
6.0      8
4.5      7
2.0      5
2.2      4
2.8      4
6.5      2
3.2      2
3.1      2
5.5      2
3.7      1
1.8      1
2.4      1
1.9      1
7.5      1
3.3      1
2.7      1
2.1      1
4.2      1
12.0     1
5.2      1
1.2      1
1.5      1
3.8      1
5.8      1
NaN count: 0

In [29]:
# check tumor_focality column
print(clinical['tumor_focality'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['tumor_focality'].isna().sum()}")

tumor_focality
Unifocal      105
Multifocal      6
NaN count: 0

In [30]:
# check smoking_history column
print(clinical['tobacco_smoking_history'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['tobacco_smoking_history'].isna().sum()}")

tobacco_smoking_history
Lifelong non-smoker: Less than 100 cigarettes smoked in lifetime    46
Current smoker: Includes daily and non-daily smokers                34
Current reformed smoker, more than 15 years                         16
Current reformed smoker within past 15 years                        12
Smoking history not available                                        3
NaN count: 0

In [31]:
# check bmi column
print(clinical['bmi'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['bmi'].isna().sum()}")

bmi
16.61    5
20.20    2
17.30    2
20.05    2
17.99    2
23.03    2
19.53    2
21.37    1
18.73    1
21.76    1
22.03    1
28.67    1
30.62    1
29.37    1
34.08    1
36.10    1
34.61    1
20.99    1
26.08    1
22.77    1
27.45    1
29.21    1
25.12    1
39.05    1
31.35    1
21.75    1
29.10    1
16.91    1
61.62    1
40.11    1
40.67    1
24.20    1
23.73    1
28.09    1
35.03    1
22.60    1
31.43    1
32.53    1
22.55    1
27.27    1
28.69    1
21.92    1
25.42    1
29.63    1
17.72    1
22.84    1
16.76    1
28.35    1
25.71    1
22.21    1
26.00    1
28.00    1
29.06    1
19.47    1
17.65    1
21.26    1
24.06    1
20.55    1
20.78    1
24.22    1
18.08    1
21.72    1
22.15    1
23.83    1
19.13    1
23.65    1
28.50    1
22.43    1
25.37    1
19.92    1
20.03    1
17.97    1
20.94    1
25.15    1
17.93    1
18.75    1
29.90    1
27.37    1
25.06    1
31.74    1
24.01    1
21.89    1
26.23    1
24.17    1
22.22    1
22.23    1
23.50    1
20.57    1
23.31    1
29.75    1
21.97    1
25.08    1
27.99    1
23.80    1
27.18    1
23.42    1
24.51    1
23.30    1
23.89    1
21.93    1
24.69    1
NaN count: 0

In [33]:
# check alcohol_consumption column
print(clinical['alcohol_consumption'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['alcohol_consumption'].isna().sum()}")

alcohol_consumption
Alcohol consumption equal to or less than 2 drinks per day for men and 1 drink or less per day for women    49
Lifelong non-drinker                                                                                        46
Alcohol consumption history not available                                                                   10
Alcohol consumption more than 2 drinks per day for men and more than 1 drink per day for women               4
Consumed alcohol in the past, but currently a non-drinker                                                    2
NaN count: 0

In [34]:
# check ethnicity_race_ancestry_identified column
print(clinical['ethnicity_race_ancestry_identified'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['ethnicity_race_ancestry_identified'].isna().sum()}")

ethnicity_race_ancestry_identified
Asian                         46
Caucasian                     36
Han                           18
European                       5
Hispanic                       2
Patient declined to state.     1
Non Hispanic                   1
Non-Hispanic                   1
Black                          1
NaN count: 0

In [ ]:
# check tumor_laterality column
print(clinical['tumor_laterality'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['tumor_laterality'].isna().sum()}")

tumor_laterality
Right    62
Left     45
NaN       4
NaN count: 4

In [36]:
# check tumor_site column
print(clinical['tumor_site'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['tumor_site'].isna().sum()}")

tumor_site
Upper Lobe     45
Other          33
Lower Lobe     31
Middle Lobe     2
NaN count: 0

In [37]:
# check pathological_staging_primary_tumor column
print(clinical['pathologic_staging_primary_tumor_pt'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['pathologic_staging_primary_tumor_pt'].isna().sum()}")

pathologic_staging_primary_tumor_pt
pT2a                                                                                                                                                                                 62
pT1b                                                                                                                                                                                 19
pT3                                                                                                                                                                                  13
pT1a                                                                                                                                                                                  9
pT2b                                                                                                                                                                                  7
pT2a: Tumor> 3 cm but <= 4 cm in greatest dimension or tumor involving the main bronchus, invading the visceral pleura and with associated atelectasis or obstructive pneumonitis     1
NaN count: 0

In [38]:
# check number_of_lymph_nodes_examined column
print(clinical['number_of_lymph_nodes_examined'].value_counts(dropna=False).to_string())
print(f"NaN count: {clinical['number_of_lymph_nodes_examined'].isna().sum()}")

number_of_lymph_nodes_examined
7     12
8      9
4      8
9      6
10     6
1      6
14     6
2      5
12     5
3      4
6      4
13     4
11     4
16     4
17     4
15     4
5      3
20     2
27     2
28     2
26     1
32     1
19     1
0      1
21     1
24     1
34     1
31     1
37     1
23     1
39     1
NaN count: 0